In [1]:
# Importing libraries
import numpy as np

### 1. Write a function so that the columns of the output matrix are powers of the input vector. 

### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing=False, the i-th output column is the input vector raised element-wise to the power of N-i-1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermode.

In [24]:
def vandermode_matrix(ip_arr,n,increasing=False):
    vad_matx = np.array([i**(n-j-1) for i in ip_arr for j in range(n)]).reshape(ip_arr.size,n)
    return vad_matx

print("\n------------------------------OUTPUT---------------------------------------\n")
arr = np.array([2,3,4,5])
no_of_col = 5
op_matx = vandermode_matrix(arr,no_of_col,False)

print("The input array is:",arr,"\n")
print("Number of columns in the output matrix is:",no_of_col,"\n")
print("Vander matrix of the input array in the decreasing order of powers:\n\n",op_matx)


------------------------------OUTPUT---------------------------------------

The input array is: [2 3 4 5] 

Number of columns in the output matrix is: 5 

Vander matrix of the input array in the decreasing order of powers:

 [[ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


### 2. Write a function to find moving average in an array over a window:- 

     Test it over [3,5,7,2,8,10,11,65,72,81,99,100,150] and window of 3.

In [7]:
a1 = np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
len(a1)

13

In [8]:
def mov_avg(x,w):
    for m in range(len(x)-(w-1)):
        yield sum(np.ones(w) * x[m:m+w]) / w

In [10]:
mv_avg = np.array(list(mov_avg(a1,3)))
mv_avg

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])